# Usa un'immagine base leggera di Node.js
FROM node:16-alpine

# Imposta la cartella di lavoro
WORKDIR /app

# Copia i file package.json e package-lock.json (se esistono)
COPY package*.json ./

# Installa le dipendenze
RUN npm install

# Copia il resto del codice
COPY . .

# Esponi la porta su cui gira l'app
EXPOSE 3000

# Comando per avviare l'app
CMD ["node", "index.js"]
